import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';

class AppStrings {
  const AppStrings(this.locale);

  final Locale locale;
  bool get isZh => locale.languageCode == 'zh';
  String t(String key) =>
      (_values[locale.languageCode] ?? _values['zh']!)[key] ?? key;

  static const supportedLocales = [Locale('zh'), Locale('en')];
  static AppStrings of(BuildContext context) =>
      Localizations.of<AppStrings>(context, AppStrings)!;

  static const _values = <String, Map<String, String>>{
    'zh': {
      'home': '首页',
      'flights': '航迹',
      'stats': '统计',
      'profile': '我的',
      'addFlight': '记录飞行',
      'editFlight': '编辑飞行',
      'saveChanges': '保存修改',
      'map': '我的飞行旅迹',
      'mapSubtitle': '把每一次起落，留在地图上。',
      'flightMap': '飞行地图',
      'travelMap': '旅行足迹',
      'travelStats': '旅行足迹统计',
      'visitedCities': '到访城市',
      'visitedCountries': '到访国家',
      'addPlace': '添加足迹',
      'addPlaceHint': '选择去过的城市，地图会点亮对应行政区。',
      'addFromPhotos': '从相册添加',
      'photoFootprintTitle': '从相册添加足迹',
      'photoFootprintHint': '自动扫描整个相册的照片定位，不上传原图；同一城市只添加一次。',
      'photoFootprintSelected': '已选择 {count} 张',
      'photoFootprintSelectedLabel': '相册照片',
      'photoFootprintAdd': '添加 {count} 个足迹',
      'photoFootprintLoading': '正在读取相册…',
      'photoFootprintScanning': '正在扫描整个相册…\n已读取 {scanned}/{total} 张',
      'photoFootprintScanTitle': '正在整理相册足迹',
      'photoFootprintStageScan': '扫描相册',
      'photoFootprintStageLocation': '读取照片定位',
      'photoFootprintStageMatch': '匹配城市并去重',
      'photoFootprintPhotoProgress': '已处理 {processed}/{total} 张照片',
      'photoFootprintCitiesFound': '已发现 {count} 个城市',
      'photoFootprintLocalOnly': '仅在本机读取定位，不上传照片',
      'photoFootprintSummary': '{count} 个城市可添加，已自动过滤无定位和重复照片',
      'photoFootprintSelectionSummary': '已选择 {selected}/{total} 个城市，点击卡片取消误识别',
      'photoFootprintAddAll': '添加全部 {count} 个足迹',
      'photoFootprintPermissionHint': '需要相册访问权限，才能读取照片的拍摄位置。',
      'photoFootprintOpenSettings': '打开系统设置',
      'photoFootprintUnsupported': '当前平台暂不支持读取系统相册位置',
      'photoFootprintNoPhotos': '相册里没有可读取的照片',
      'photoFootprintNoLocation': '这张照片没有位置信息',
      'photoFootprintNoGps': '无定位',
      'photoFootprintLocated': '有定位',
      'photoFootprintNoImportable': '没有发现可添加的定位足迹',
      'photoFootprintLoadFailed': '读取相册失败，请重试',
      'photoFootprintDateUnknown': '日期未知',
      'selected': '已选',
      'selectAll': '全选',
      'deselectAll': '取消全选',
      'clear': '清除',
      'retry': '重试',
      'selectCity': '选择城市',
      'searchCity': '搜索城市、机场或国家',
      'visitedDate': '到访日期',
      'savePlace': '保存足迹',
      'selectFootprint': '选择要操作的足迹',
      'deleteFootprintTitle': '删除这个足迹？',
      'deleteFootprintMessage': '删除后该城市会从旅行足迹中移除，地图点亮状态也会重新计算。',
      'footprintDeleted': '足迹已删除',
      'undo': '撤销',
      'cityRequired': '请先选择城市',
      'noCityResults': '没有找到匹配的城市',
      'fullscreen': '全屏地图',
      'landscapeFullscreen': '横屏沉浸',
      'exitLandscape': '退出横屏',
      'close': '关闭',
      'worldExplorer': '探索世界',
      'chinaExplorer': '探索中国',
      'explorationHint': '只统计已经点亮的行政区。',
      'visitedRegions': '已点亮行政区',
      'totalDistance': '总里程',
      'nextTrip': '下一趟旅程',
      'viewAll': '查看全部',
      'noFlights': '还没有飞行记录',
      'noFlightsHint': '记录第一段航程，地图与统计会自动生成。',
      'startRecord': '记录第一段飞行',
      'flightRecords': '飞行记录',
      'flightRecordsSubtitle': '每一段航程，都是旅途的坐标。',
      'upcoming': '待出行',
      'completed': '已结束',
      'flightStatus': '航程状态',
      'noUpcomingFlights': '暂无待出行航程',
      'noUpcomingFlightsHint': '添加未来日期的航程，它会出现在这里。',
      'noCompletedFlights': '暂无已结束航程',
      'noCompletedFlightsHint': '完成第一段飞行后，记录会出现在这里。',
      'all': '全部',
      'departure': '出发地',
      'arrival': '目的地',
      'takeoff': '起飞',
      'landing': '降落',
      'date': '日期',
      'flightDate': '航班日期',
      'requiredInfo': '航空公司与航班号必填',
      'requiredHint': '填写航司与航班号，机场等信息优先自动补全，也可手动修改。',
      'moreDetails': '更多信息',
      'optionalInfo': '机型、时长等可选',
      'autoFillFlight': '自动补全航班信息',
      'lookingUpFlight': '正在查询航班…',
      'flightLookupSuccess': '已从航班数据源补全可用信息',
      'flightLookupNoResult': '暂未找到航班资料，可继续手动填写',
      'flightLookupFailed': '航班数据源暂时不可用，可继续手动填写',
      'missingRequired': '请补充航空公司、航班号、出发地和目的地。',
      'requiredField': '必填',
      'airline': '航空公司',
      'flightNumber': '航班号',
      'airlineFlight': '航空公司 + 航班号',
      'airlineFlightHint': '例如：南方航空 CZ679',
      'aircraft': '飞机机型',
      'duration': '飞行时长（分钟）',
      'flightDuration': '飞行时长',
      'durationPending': '待补全',
      'distance': '里程（公里）',
      'seat': '座位',
      'cabin': '舱位',
      'note': '备注',
      'economy': '经济舱',
      'save': '保存飞行',
      'selectAirport': '选择机场',
      'searchAirport': '搜索代码、城市、国家或机场',
      'countryAirportCount': '{count} 个机场 · 点击查看',
      'countryAirports': '{country} · {count} 个机场',
      'cancel': '取消',
      'delete': '删除',
      'edit': '编辑',
      'deleteFlight': '删除这段飞行？',
      'deleteHint': '删除后只能通过备份恢复。',
      'statistics': '飞行统计',
      'statsSubtitle': '数字会记住，那些当时没来得及细看的远方。',
      'flightsCount': '飞行次数',
      'airportsCount': '覆盖机场',
      'longestFlight': '最长航段',
      'aircraftCollection': '我的机型图鉴',
      'aircraftTypesCount': '{count} 种机型',
      'aircraftCollectionEmpty': '填写机型后会自动生成图鉴。',
      'rankingEntries': '{count} 项',
      'rankingEmpty': '暂无数据',
      'airlineRanking': '航司排行',
      'cities': '城市统计',
      'countries': '国家统计',
      'times': '次',
      'km': '公里',
      'localData': '本地数据',
      'localOnly': '数据只保存在这台设备',
      'exportBackup': '导出备份',
      'importBackup': '导入备份',
      'importWebData': '导入网页数据',
      'importWebHint': '网页 JSON 或本地备份',
      'importExcel': '导入 Excel 行程',
      'importExcelHint': '航旅纵横表格（.xlsx、.xls 或 .csv）',
      'importCalendar': '从系统日历导入',
      'importCalendarHint': '识别航旅纵横写入的航班日程',
      'calendarReading': '正在读取系统日历',
      'calendarPermissionDenied': '需要日历读取权限才能导入航班日程',
      'calendarUnsupported': '当前平台暂不支持读取系统日历',
      'calendarNoFlights': '没有找到可识别的航班日程',
      'calendarImportTitle': '日历航程预览',
      'calendarEventsRead': '已读取 {count} 个日历事件',
      'calendarFlightsFound': '识别到 {count} 条航程',
      'calendarConfirm': '导入选中的航程',
      'calendarImporting': '正在导入日历航程',
      'calendarImportDone': '日历航程导入完成',
      'calendarImportDoneDetail':
          '新增 {added} 条\n更新 {updated} 条\n未变化 {unchanged} 条\n未覆盖 {skipped} 条',
      'calendarNoSelection': '请至少选择一条航程',
      'calendarSource': '系统日历 · 航旅纵横',
      'spreadsheetImportTitle': '导入 Excel 行程',
      'spreadsheetRecognizing': '正在识别表格',
      'spreadsheetPreview': '导入预览',
      'spreadsheetSheet': '工作表',
      'spreadsheetValidRows': '可导入航程',
      'spreadsheetIssueRows': '需要检查行',
      'spreadsheetNoIssues': '没有需要检查的行程',
      'spreadsheetAmbiguousAirport': '城市包含多个机场，已按常用机场匹配',
      'spreadsheetNoRows': '没有可导入的有效航程',
      'spreadsheetConfirm': '确认导入',
      'spreadsheetConflicts': '待确认覆盖',
      'spreadsheetOverwriteTitle': '发现已有航程数据',
      'spreadsheetOverwriteMessage': '有 {count} 条已有记录与表格内容不同。要用航旅纵横数据覆盖吗？',
      'spreadsheetKeepExisting': '保留已有',
      'spreadsheetOverwrite': '覆盖并导入',
      'spreadsheetImporting': '正在导入航程',
      'spreadsheetImportingHint': '正在写入本地记录，请稍候',
      'spreadsheetStageReading': '读取表格',
      'spreadsheetStageMatching': '匹配机场',
      'spreadsheetStageReady': '准备导入',
      'spreadsheetImportDone': '导入完成',
      'spreadsheetImportDoneDetail':
          '新增 {added} 条\n更新 {updated} 条\n未变化 {unchanged} 条\n未覆盖 {skipped} 条',
      'spreadsheetImported': '导入完成：新增 {count} 条航程',
      'spreadsheetIssuesHint': '部分行无法识别，已跳过。请检查日期、航班号和城市名称。',
      'cloudSync': '云端同步',
      'notConfigured': '未配置',
      'cloudConnected': '已连接',
      'cloudReady': '等待同步',
      'cloudSyncing': '同步中',
      'cloudSynced': '已同步',
      'cloudSyncFailed': '同步失败',
      'cloudSyncTitle': '连接你的云端',
      'cloudSetupHint': '可选连接自己部署的 Cloudflare Worker + D1。未连接时，数据仍只保存在本机。',
      'cloudEndpoint': 'Worker 地址',
      'cloudEndpointHint': '建议使用 Cloudflare 自定义域名；workers.dev 在部分手机网络可能无法访问',
      'changeCloudEndpoint': '切换同步地址',
      'changeCloudEndpointTitle': '切换同步地址',
      'changeCloudEndpointHint': '适用于同一资料库的另一个入口，例如 Pages 地址。设备令牌不会改变。',
      'changeCloudEndpointConfirm': '验证并切换',
      'cloudBootstrapSecret': '初始化密钥',
      'cloudBootstrapHint': '部署 Worker 时设置的 BOOTSTRAP_SECRET',
      'cloudRecoveryCode': '恢复码',
      'cloudRecoveryHint': '以 ffr1. 开头的资料库恢复码',
      'createCloud': '新建云端',
      'restoreCloud': '恢复已有云端',
      'connectCloud': '连接云端',
      'syncNow': '本地同步到云端',
      'localToCloud': '本地覆盖云端',
      'localToCloudHint': '以这台设备的记录为准，覆盖云端快照。',
      'restoreFromCloud': '云端恢复到本地',
      'restoreFromCloudHint': '用云端快照替换本机记录，适合新设备或换机。',
      'restoreCloudTitle': '确认恢复云端数据？',
      'restoreCloudMessage': '恢复会替换本机现有的飞行和足迹记录，不能自动合并。',
      'restoreCloudConfirm': '替换本地并恢复',
      'cloudRestored': '云端数据已恢复到本地',
      'lastSynced': '最近同步',
      'neverSynced': '尚未同步',
      'viewRecoveryCode': '查看恢复码',
      'copyRecoveryCode': '复制恢复码',
      'recoveryCodeSaved': '恢复码已复制，请离线保存',
      'recoveryCodeWarning': '恢复码是资料库主钥匙，只显示在你的设备上。不要放进截图、源码或公开仓库。',
      'noRecoveryCode': '本机没有保存恢复码；已连接设备仍可同步。',
      'disconnectCloud': '断开云端',
      'disconnectCloudHint': '只会清除本机的云端连接，不会删除云端或本地记录。',
      'cloudConflict': '检测到其他设备更新，本次已按本地记录覆盖云端。',
      'cloudNotConfigured': '请先填写 Worker 地址和凭据',
      'cloudSnapshotUnsupported': '云端快照格式不兼容，请先导出备份。',
      'settings': '偏好设置',
      'travellerName': '用户名',
      'travellerNameHint': '会显示在分享卡片上',
      'enterTravellerName': '填写用户名',
      'travellerNameEmpty': '未设置',
      'language': '语言',
      'chinese': '中文',
      'english': 'English',
      'units': '距离单位',
      'about': '关于',
      'version': '版本 1.0.0',
      'privacy': '无需登录 · 无追踪 · 本地优先',
      'checkForUpdates': '检查更新',
      'checkForUpdatesHint': '从 GitHub 获取最新版本',
      'checkingForUpdates': '正在检查…',
      'upToDate': '已是最新版本',
      'updateAvailable': '发现新版本',
      'updateCheckFailed': '暂时无法检查更新',
      'githubProject': 'GitHub 项目',
      'githubProjectHint': '查看源码与版本发布',
      'githubProjectNotConfigured': '项目地址待配置',
      'openRelease': '打开发布页',
      'githubOpenFailed': '无法打开 GitHub 页面',
      'backupSuccess': '备份已生成',
      'importSuccess': '数据导入成功',
      'operationFailed': '操作失败',
      'emptyStats': '记录飞行后，这里会生成趋势与排行。',
      'unknown': '未填写',
      'tapToChoose': '点击选择',
      'route': '航线',
      'localFirst': '独立、本地优先的飞行日记。',
    },
    'en': {
      'home': 'Home',
      'flights': 'Flights',
      'stats': 'Stats',
      'profile': 'Me',
      'addFlight': 'Add Flight',
      'editFlight': 'Edit Flight',
      'saveChanges': 'Save Changes',
      'map': 'My Flight Map',
      'mapSubtitle': 'Keep every takeoff and landing on your map.',
      'flightMap': 'Flight Map',
      'travelMap': 'Travel Footprint',
      'travelStats': 'Travel Footprint Stats',
      'visitedCities': 'Visited cities',
      'visitedCountries': 'Visited countries',
      'addPlace': 'Add footprint',
      'addPlaceHint': 'Choose a city you have visited to light up its region.',
      'addFromPhotos': 'Add from Photos',
      'photoFootprintTitle': 'Add footprints from Photos',
      'photoFootprintHint': 'Scan the entire photo library for GPS locally. Originals are never uploaded; each city is added once.',
      'photoFootprintSelected': '{count} selected',
      'photoFootprintSelectedLabel': 'Photo',
      'photoFootprintAdd': 'Add {count} footprints',
      'photoFootprintLoading': 'Reading your photo library…',
      'photoFootprintScanning':
          'Scanning the entire photo library…\nRead {scanned}/{total} photos',
      'photoFootprintScanTitle': 'Organizing your photo footprint',
      'photoFootprintStageScan': 'Scan photo library',
      'photoFootprintStageLocation': 'Read photo locations',
      'photoFootprintStageMatch': 'Match and deduplicate cities',
      'photoFootprintPhotoProgress': '{processed}/{total} photos processed',
      'photoFootprintCitiesFound': '{count} cities found',
      'photoFootprintLocalOnly':
          'Location data is read on-device; photos are never uploaded',
      'photoFootprintSummary': '{count} cities ready; photos without location and duplicates were filtered',
      'photoFootprintSelectionSummary': '{selected}/{total} cities selected; tap a card to remove a wrong match',
      'photoFootprintAddAll': 'Add all {count} footprints',
      'photoFootprintPermissionHint':
          'Photo access is needed to read where a photo was taken.',
      'photoFootprintOpenSettings': 'Open Settings',
      'photoFootprintUnsupported':
          'This platform cannot read photo locations yet',
      'photoFootprintNoPhotos': 'No readable photos found',
      'photoFootprintNoLocation': 'This photo has no location data',
      'photoFootprintNoGps': 'No location',
      'photoFootprintLocated': 'Located',
      'photoFootprintNoImportable':
          'No photo locations can be added as footprints',
      'photoFootprintLoadFailed':
          'Could not read the photo library. Try again.',
      'photoFootprintDateUnknown': 'Date unknown',
      'selected': 'Selected',
      'selectAll': 'Select all',
      'deselectAll': 'Clear selection',
      'clear': 'Clear',
      'retry': 'Retry',
      'selectCity': 'Select city',
      'searchCity': 'Search city, airport or country',
      'visitedDate': 'Visited date',
      'savePlace': 'Save footprint',
      'selectFootprint': 'Choose a footprint',
      'deleteFootprintTitle': 'Delete this footprint?',
      'deleteFootprintMessage': 'This city will be removed from your travel footprint and the map will recalculate its highlights.',
      'footprintDeleted': 'Footprint deleted',
      'undo': 'Undo',
      'cityRequired': 'Choose a city first',
      'noCityResults': 'No matching city found',
      'fullscreen': 'Full-screen map',
      'landscapeFullscreen': 'Landscape fullscreen',
      'exitLandscape': 'Exit landscape',
      'close': 'Close',
      'worldExplorer': 'Explore the world',
      'chinaExplorer': 'Explore China',
      'explorationHint': 'Only visited regions count toward progress.',
      'visitedRegions': 'regions lit',
      'totalDistance': 'Total Distance',
      'nextTrip': 'Next Trip',
      'viewAll': 'View all',
      'noFlights': 'No flights yet',
      'noFlightsHint': 'Add your first flight to build maps and statistics.',
      'startRecord': 'Add first flight',
      'flightRecords': 'Flight Records',
      'flightRecordsSubtitle': 'Every route is a coordinate of your journey.',
      'upcoming': 'Upcoming',
      'completed': 'Completed',
      'flightStatus': 'Flight status',
      'noUpcomingFlights': 'No upcoming flights',
      'noUpcomingFlightsHint': 'Add a future flight and it will appear here.',
      'noCompletedFlights': 'No completed flights',
      'noCompletedFlightsHint':
          'Completed flights will appear here after you fly.',
      'all': 'All',
      'departure': 'From',
      'arrival': 'To',
      'takeoff': 'Takeoff',
      'landing': 'Landing',
      'date': 'Date',
      'flightDate': 'Flight date',
      'requiredInfo': 'Airline and flight number required',
      'requiredHint': 'Enter the airline and flight number. Airports and other details can be auto-filled or edited.',
      'moreDetails': 'More details',
      'optionalInfo': 'Aircraft, duration and more (optional)',
      'autoFillFlight': 'Auto-fill flight details',
      'lookingUpFlight': 'Looking up flight…',
      'flightLookupSuccess': 'Available flight details were filled in',
      'flightLookupNoResult':
          'No flight details found; you can continue manually',
      'flightLookupFailed':
          'Flight data is temporarily unavailable; you can continue manually',
      'missingRequired':
          'Please add the airline, flight number, origin and destination.',
      'requiredField': 'Required',
      'airline': 'Airline',
      'flightNumber': 'Flight number',
      'airlineFlight': 'Airline + flight number',
      'airlineFlightHint': 'For example: China Southern CZ679',
      'aircraft': 'Aircraft',
      'duration': 'Duration (minutes)',
      'flightDuration': 'Flight time',
      'durationPending': 'Pending',
      'distance': 'Distance (km)',
      'seat': 'Seat',
      'cabin': 'Cabin',
      'note': 'Notes',
      'economy': 'Economy',
      'save': 'Save Flight',
      'selectAirport': 'Select Airport',
      'searchAirport': 'Search code, city, country or airport',
      'countryAirportCount': '{count} airports · Tap to view',
      'countryAirports': '{country} · {count} airports',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'deleteFlight': 'Delete this flight?',
      'deleteHint': 'It can only be restored from a backup.',
      'statistics': 'Flight Statistics',
      'statsSubtitle':
          'Numbers remember the places you barely had time to see.',
      'flightsCount': 'Flights',
      'airportsCount': 'Airports',
      'longestFlight': 'Longest',
      'aircraftCollection': 'Aircraft Collection',
      'aircraftTypesCount': '{count} aircraft types',
      'aircraftCollectionEmpty': 'Aircraft cards appear after you add a model.',
      'rankingEntries': '{count} entries',
      'rankingEmpty': 'No data yet',
      'airlineRanking': 'Airline Ranking',
      'cities': 'Cities',
      'countries': 'Countries',
      'times': 'flights',
      'km': 'km',
      'localData': 'Local Data',
      'localOnly': 'Stored only on this device',
      'exportBackup': 'Export Backup',
      'importBackup': 'Import Backup',
      'importWebData': 'Import web data',
      'importWebHint': 'Web JSON or local backup',
      'importExcel': 'Import Excel itinerary',
      'importExcelHint': 'Umetrip spreadsheet (.xlsx, .xls or .csv)',
      'importCalendar': 'Import from calendar',
      'importCalendarHint': 'Recognize flight events written by Umetrip',
      'calendarReading': 'Reading system calendar',
      'calendarPermissionDenied':
          'Calendar read permission is needed to import flights',
      'calendarUnsupported':
          'Reading the system calendar is not supported on this platform',
      'calendarNoFlights': 'No recognizable flight events found',
      'calendarImportTitle': 'Calendar flight preview',
      'calendarEventsRead': 'Read {count} calendar events',
      'calendarFlightsFound': 'Found {count} flights',
      'calendarConfirm': 'Import selected flights',
      'calendarImporting': 'Importing calendar flights',
      'calendarImportDone': 'Calendar import complete',
      'calendarImportDoneDetail': 'Added {added}\nUpdated {updated}\nUnchanged {unchanged}\nNot overwritten {skipped}',
      'calendarNoSelection': 'Select at least one flight',
      'calendarSource': 'System calendar · Umetrip',
      'spreadsheetImportTitle': 'Import Excel itinerary',
      'spreadsheetRecognizing': 'Reading spreadsheet',
      'spreadsheetPreview': 'Import preview',
      'spreadsheetSheet': 'Sheet',
      'spreadsheetValidRows': 'Flights ready',
      'spreadsheetIssueRows': 'Needs review',
      'spreadsheetNoIssues': 'No rows need review',
      'spreadsheetAmbiguousAirport':
          'Multiple airports found; the common airport was selected',
      'spreadsheetNoRows': 'No valid flights found',
      'spreadsheetConfirm': 'Import flights',
      'spreadsheetConflicts': 'Needs overwrite',
      'spreadsheetOverwriteTitle': 'Existing itinerary found',
      'spreadsheetOverwriteMessage': '{count} existing flights differ from the spreadsheet. Replace them with the Umetrip data?',
      'spreadsheetKeepExisting': 'Keep existing',
      'spreadsheetOverwrite': 'Overwrite & import',
      'spreadsheetImporting': 'Importing flights',
      'spreadsheetImportingHint': 'Saving local flight records',
      'spreadsheetStageReading': 'Read sheet',
      'spreadsheetStageMatching': 'Match airports',
      'spreadsheetStageReady': 'Prepare import',
      'spreadsheetImportDone': 'Import complete',
      'spreadsheetImportDoneDetail': 'Added {added}\nUpdated {updated}\nUnchanged {unchanged}\nNot overwritten {skipped}',
      'spreadsheetImported': 'Import complete: {count} flights added',
      'spreadsheetIssuesHint': 'Some rows could not be read and were skipped. Check dates, flight numbers and cities.',
      'cloudSync': 'Cloud Sync',
      'notConfigured': 'Not configured',
      'cloudConnected': 'Connected',
      'cloudReady': 'Ready to sync',
      'cloudSyncing': 'Syncing',
      'cloudSynced': 'Synced',
      'cloudSyncFailed': 'Sync failed',
      'cloudSyncTitle': 'Connect your cloud',
      'cloudSetupHint': 'Optionally connect your own Cloudflare Worker + D1. Without it, data stays on this device.',
      'cloudEndpoint': 'Worker endpoint',
      'cloudEndpointHint': 'A Cloudflare custom domain is recommended; workers.dev may be unreachable on some mobile networks',
      'changeCloudEndpoint': 'Change sync endpoint',
      'changeCloudEndpointTitle': 'Change sync endpoint',
      'changeCloudEndpointHint': 'Use this for another entry point to the same vault, such as a Pages URL. The device token stays the same.',
      'changeCloudEndpointConfirm': 'Verify and switch',
      'cloudBootstrapSecret': 'Bootstrap secret',
      'cloudBootstrapHint':
          'The BOOTSTRAP_SECRET configured when deploying the Worker',
      'cloudRecoveryCode': 'Recovery code',
      'cloudRecoveryHint': 'The vault recovery code that starts with ffr1.',
      'createCloud': 'Create cloud',
      'restoreCloud': 'Restore cloud',
      'connectCloud': 'Connect cloud',
      'syncNow': 'Local to cloud',
      'localToCloud': 'Overwrite cloud with local',
      'localToCloudHint':
          'Use this device as the source of truth for the cloud snapshot.',
      'restoreFromCloud': 'Restore cloud to local',
      'restoreFromCloudHint':
          'Replace local records with the cloud snapshot for a new device.',
      'restoreCloudTitle': 'Restore cloud data?',
      'restoreCloudMessage': 'This replaces the flights and footprints on this device. They will not be merged automatically.',
      'restoreCloudConfirm': 'Replace local & restore',
      'cloudRestored': 'Cloud data restored to this device',
      'lastSynced': 'Last sync',
      'neverSynced': 'Not synced yet',
      'viewRecoveryCode': 'View recovery code',
      'copyRecoveryCode': 'Copy recovery code',
      'recoveryCodeSaved': 'Recovery code copied. Save it offline.',
      'recoveryCodeWarning': 'The recovery code is the vault master key and is shown only on your device. Never put it in screenshots, source code or a public repository.',
      'noRecoveryCode': 'No recovery code is saved on this device; the connected device can still sync.',
      'disconnectCloud': 'Disconnect cloud',
      'disconnectCloudHint': 'This clears only the local cloud connection. It does not delete cloud or local records.',
      'cloudConflict': 'Another device updated; this sync kept the local records and overwrote the cloud snapshot.',
      'cloudNotConfigured': 'Enter a Worker endpoint and credential first',
      'cloudSnapshotUnsupported':
          'The cloud snapshot format is not compatible. Export a backup first.',
      'settings': 'Preferences',
      'travellerName': 'Username',
      'travellerNameHint': 'Shown on your share card',
      'enterTravellerName': 'Set username',
      'travellerNameEmpty': 'Not set',
      'language': 'Language',
      'chinese': '中文',
      'english': 'English',
      'units': 'Distance unit',
      'about': 'About',
      'version': 'Version 1.0.0',
      'privacy': 'No login · No tracking · Local first',
      'checkForUpdates': 'Check for updates',
      'checkForUpdatesHint': 'Get the latest version from GitHub',
      'checkingForUpdates': 'Checking…',
      'upToDate': 'You are up to date',
      'updateAvailable': 'New version available',
      'updateCheckFailed': 'Update check unavailable',
      'githubProject': 'GitHub project',
      'githubProjectHint': 'View source and releases',
      'githubProjectNotConfigured': 'Project link not configured',
      'openRelease': 'Open release page',
      'githubOpenFailed': 'Could not open GitHub',
      'backupSuccess': 'Backup created',
      'importSuccess': 'Data imported',
      'operationFailed': 'Operation failed',
      'emptyStats': 'Add flights to generate trends and rankings.',
      'unknown': 'Not set',
      'tapToChoose': 'Tap to choose',
      'route': 'Route',
      'localFirst': 'An independent, local-first flight journal.',
    },
  };
}

class AppStringsDelegate extends LocalizationsDelegate<AppStrings> {
  const AppStringsDelegate();
  @override
  bool isSupported(Locale locale) => AppStrings.supportedLocales.any(
    (e) => e.languageCode == locale.languageCode,
  );
  @override
  Future<AppStrings> load(Locale locale) =>
      SynchronousFuture(AppStrings(locale));
  @override
  bool shouldReload(AppStringsDelegate old) => false;
}

extension AppStringsContext on BuildContext {
  AppStrings get strings => AppStrings.of(this);
}
